AWSTemplateFormatVersion: '2010-09-09'
Description: Online Ledger Infrastructure Stack

Parameters:
  Stage:
    Description: Application deployment stage.
    Type: String
    Default: LOCAL
    AllowedValues:
    - PROD
    - TEST
    - LOCAL

  Region:
    Description: AWS region
    Type: String
    Default: us-east-1
    AllowedValues:
    - us-east-1
    - us-east-2
    - eu-west-1
    - eu-west-2

Resources:
  LedgerBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: Ledger
      VersioningConfiguration:
        Status: Disabled

  SampleFunc:
    Type: "AWS::Lambda::Function"

    Properties:
      FunctionName: "Sample"
      Handler: "basic.handler"
      Environment:
        Variables:
          AWS_ACCESS_KEY_ID: ""
          AWS_SECRET_ACCESS_KEY: ""
          AWS_REGION: !Ref Region
          S3_ENDPOINT_URL: http://localhost:4572
          BUCKET_NAME: Ledger
      Role:
        Fn::GetAtt:
          - "LambdaExecutionRole"
          - "Arn"
      Code:
        S3Bucket: "__local__"
        S3Key: "/opt/lambda"
      Runtime: "python3.8"
      Timeout: 25
      TracingConfig:
        Mode: "Active"
