AWSTemplateFormatVersion: '2010-09-09'
Description: Online Ledger Infrastructure Stack

Resources:
  LedgerBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: Ledger
      VersioningConfiguration:
        Status: Disabled

  ServerlessDeploymentBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: online-ledger-service-deployment-bucket
      VersioningConfiguration:
        Status: Disabled
