FROM python:3.7-alpine

ENV PYTHONUNBUFFERED 1

# installing gcc
RUN apk add build-base

# misc
RUN apk add bash git

RUN pip install --upgrade pip

RUN pip install aloe==0.1.16 nose==1.3.7 requests==2.20.0
