FROM python:3.7-alpine

ENV PYTHONUNBUFFERED 1

# installing gcc
RUN apk add build-base

# libs for matplotlib
RUN apk add freetype-dev
RUN apk add libpng-dev

# misc
RUN apk add postgresql-client postgresql-dev bash git

RUN pip install \
    Django==2.1.1 \
    django-extensions==2.1.3 \
    redis==2.10.6 \
    jupyter==1.0.0 \
    pandas==0.23.4 \
    matplotlib==2.2.2 \
    psycopg2==2.7.5 \
    djangorestframework==3.8.2 \
    django-filter==2.0.0

RUN mkdir /code

RUN pip install lettuce==0.2.23
