version: '3.7'
services:

  localstack:
    image: localstack/localstack
    ports:
      - "4567-4584:4567-4584"
    environment:
      - SERVICES=serverless
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-local}
      - LAMBDA_REMOTE_DOCKER=${LAMBDA_REMOTE_DOCKER-False}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - START_WEB=0
    volumes:
      - type: bind
        source: "${TMPDIR:-/tmp/localstack}"
        target: /tmp/localstack
      - type: bind
        source: ./lambda
        target: /opt/lambda
