FROM python:3.7-alpine

ENV PYTHONUNBUFFERED 1

# installing gcc
RUN apk add build-base

# misc
RUN apk add bash git

RUN pip install --upgrade pip

RUN pip install behave==1.2.6 nose==1.3.7 requests==2.20.0
