version: '3'
services:

  django:
    container_name: django-server
    build:
      context: .
      dockerfile: Dockerfile-django

    image: django:latest

    restart: always
    command: /bin/bash /startup/startup.bash
    hostname: django
    environment:
      - PYTHONPATH=/django:/code
      - DJANGO_SETTINGS_MODULE=djangoapp.settings

    env_file: django.secrets

    working_dir: /startup
    volumes:
      - ./django_container:/django
      - ./django_startup:/startup
      - ./server:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - django-db
    links:
     - redis

  redis:
    container_name: redis-server
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  django-db:
    container_name: django-db
    image: postgres:10.4-alpine
    environment:
      POSTGRES_USER: oas
      POSTGRES_PASSWORD: oas
      POSTGRES_DB: oas
    ports:
      - "5432:5432"

  client:
    container_name: web-client
    build:
      context: .
      dockerfile: Dockerfile-client

    volumes:
      - ./client:/client
    depends_on:
      - django
    working_dir: /client/data
    command: bash -c "/usr/bin/env nosetests --verbosity=10 --with-gherkin /client/data/features/legal_entities/legal_entities.feature; tail -F /dev/null"
    #command: /usr/bin/env python /client/scripts/setup.py

volumes:
  redis-data:
