version: '3.7'
services:

  localstack:
    image: localstack/localstack
    ports:
      - "4567-4584:4567-4584"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-local}
      - LAMBDA_REMOTE_DOCKER=${LAMBDA_REMOTE_DOCKER-False}
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - type: bind
        source: "${TMPDIR:-/tmp/localstack}"
        target: /tmp/localstack
      - type: bind
        source: ./lambda
        target: /opt/lambda
