import logging
from pprint import pprint
from oasclient import jsonext
from oasclient import login_sequence

def init_db_full(rpcsrv):
    rpcsrv.create_legal_entity('Example', 'Example Corp','USD')
    rpcsrv.create_asset_account('100-129', 'Cash','','Example')
    rpcsrv.create_asset_account('130-139', 'Receivables','','Example')
    rpcsrv.create_asset_account('140-179', 'Inventories','','Example')
    rpcsrv.create_asset_account('180-199', 'Prepaid Expenses','','Example')
    rpcsrv.create_asset_account('200-299', 'Fixed Assets','','Example')
    rpcsrv.create_asset_account('300-399', 'Other Assets','','Example')
    rpcsrv.create_liability_account('400-429', 'Payables','','Example')
    rpcsrv.create_liability_account('430-459', 'Payroll & Withholdings','','Example')
    rpcsrv.create_liability_account('460-479', 'Accrued Expenses','','Example')
    rpcsrv.create_liability_account('600-699', 'Other Liabilities','','Example')
    rpcsrv.create_liability_account('900-999', 'Equity','','Example')
    rpcsrv.create_income_account('1000-1999', 'Revenue','','Example')
    rpcsrv.create_expense_account('2000-2999', 'Cost of Sales','','Example')
    rpcsrv.create_expense_account('3000-3999', 'Manufacturing Expense','','Example')
    rpcsrv.create_expense_account('5000-5999', 'Engineering Expense','','Example')
    rpcsrv.create_expense_account('6000-6999', 'Selling Expense','','Example')
    rpcsrv.create_expense_account('7000-7999', 'Adminstrative Expense','','Example')
    rpcsrv.create_expense_account('8000-8999', 'Other Expense','','Example')
    rpcsrv.create_expense_account('9000-9999', 'Other Tax','','Example')
    rpcsrv.create_asset_account('101','Petty Cash','','Example')
    rpcsrv.create_asset_account('110','Cash in Bank','','Example')
    rpcsrv.create_asset_account('112','Payables Checking','','Example')
    rpcsrv.create_asset_account('115','Payroll Checking','','Example')
    rpcsrv.create_asset_account('117','Money Market','','Example')
    rpcsrv.create_asset_account('130','Receivable','','Example')
    rpcsrv.create_asset_account('132','Reinvoiceable','','Example')
    rpcsrv.create_asset_account('139','Other Receivables','','Example')
    rpcsrv.create_asset_account('140','Purchased Materials','','Example')
    rpcsrv.create_asset_account('150','Subassembly Inventory','','Example')
    rpcsrv.create_asset_account('170','Product Inventory','','Example')
    rpcsrv.create_asset_account('180','Insurance','','Example')
    rpcsrv.create_asset_account('190','Other Prepaid Expenses','','Example')
    rpcsrv.create_asset_account('210','Land','','Example')
    rpcsrv.create_asset_account('220','Buildings','','Example')
    rpcsrv.create_asset_account('221','Building Equipment','','Example')
    rpcsrv.create_asset_account('229','BE Depreciation','','Example')
    rpcsrv.create_asset_account('250','Machinery & Equipment','','Example')
    rpcsrv.create_asset_account('259','M&E Depreciation','','Example')
    rpcsrv.create_asset_account('270','Furniture & Fixtures','','Example')
    rpcsrv.create_asset_account('279','F&F Depreciation','','Example')
    rpcsrv.create_asset_account('280','Transportation Equipment','','Example')
    rpcsrv.create_asset_account('289','TE Depreciation','','Example')
    rpcsrv.create_asset_account('343','Employee Advances','','Example')
    rpcsrv.create_income_account('1100','Domestic','','Example')
    rpcsrv.create_income_account('1200','Export','','Example')
    rpcsrv.create_income_account('1900','Other Revenue','','Example')
    rpcsrv.create_expense_account('2100','Material','','Example')
    rpcsrv.create_expense_account('2200','Labor - Cost of Sale','','Example')
    rpcsrv.create_expense_account('2990','Other Cost of Sale','','Example')
    rpcsrv.create_expense_account('3210','Labor - General','','Example')
    rpcsrv.create_expense_account('3220','Labor - Area1','','Example')
    rpcsrv.create_expense_account('3230','Labor - Area2','','Example')
    rpcsrv.create_expense_account('3295','Overtime - Manufacturing','','Example')
    rpcsrv.create_expense_account('3350','Vacation - Manufacturing','','Example')
    rpcsrv.create_expense_account('3351','Vacation Rate Change - Manufacturing','','Example')
    rpcsrv.create_expense_account('3352','Bonuses - Manufacturing','','Example')
    rpcsrv.create_expense_account('3353','Holidays - Manufacturing','','Example')
    rpcsrv.create_expense_account('3410','Small Parts','','Example')
    rpcsrv.create_expense_account('3420','Other Materials','','Example')
    rpcsrv.create_expense_account('3490','Material Discounts','','Example')
    rpcsrv.create_expense_account('3520','Manufacturing Supplies','','Example')
    rpcsrv.create_expense_account('3550','Heat Light Power','','Example')
    rpcsrv.create_expense_account('3560','Freight Out','','Example')
    rpcsrv.create_expense_account('3565','Freight In','','Example')
    rpcsrv.create_expense_account('3570','Outside Services - Manufacturing','','Example')
    rpcsrv.create_expense_account('5250','Labor - Engineering','','Example')
    rpcsrv.create_expense_account('5295','Overtime - Engineering','','Example')
    rpcsrv.create_expense_account('5350','Vacation - Engineering','','Example')
    rpcsrv.create_expense_account('5351','Vacation Rate Change - Engineering','','Example')
    rpcsrv.create_expense_account('5352','Bonuses - Engineering','','Example')
    rpcsrv.create_expense_account('5353','Holidays - Engineering','','Example')
    rpcsrv.create_expense_account('5520','Supplies - Engineering','','Example')
    rpcsrv.create_expense_account('5570','Outside Services - Engineering','','Example')
    rpcsrv.create_expense_account('5580','Royalties','','Example')
    rpcsrv.create_expense_account('5990','Other Engineering Expenses','','Example')
    rpcsrv.create_expense_account('6250','Labor - Selling','','Example')
    rpcsrv.create_expense_account('6251','Commissions','','Example')
    rpcsrv.create_expense_account('6295','Overtime - Selling','','Example')
    rpcsrv.create_expense_account('6350','Vacation - Selling','','Example')
    rpcsrv.create_expense_account('6351','Vacation Rate Change - Selling','','Example')
    rpcsrv.create_expense_account('6352','Bonuses - Selling','','Example')
    rpcsrv.create_expense_account('6353','Holidays - Selling','','Example')
    rpcsrv.create_expense_account('6502','Advertising','','Example')
    rpcsrv.create_expense_account('6520','Supplies - Selling','','Example')
    rpcsrv.create_expense_account('6568','Postage','','Example')
    rpcsrv.create_expense_account('6570','Outside Services - Selling','','Example')
    rpcsrv.create_expense_account('6600','Travel & Entertainment - Selling','','Example')
    rpcsrv.create_expense_account('6660','Bad Debts','','Example')
    rpcsrv.create_expense_account('6661','Sales Allowances','','Example')
    rpcsrv.create_expense_account('7250','Labor - Administrative','','Example')
    rpcsrv.create_expense_account('7295','Overtime - Administrative','','Example')
    rpcsrv.create_expense_account('7301','FICA','','Example')
    rpcsrv.create_expense_account('7305','FUT','','Example')
    rpcsrv.create_expense_account('7306','SUT','','Example')
    rpcsrv.create_expense_account('7340','Workers Comp','','Example')
    rpcsrv.create_expense_account('7345','Employee Insurance','','Example')
    rpcsrv.create_expense_account('7348','Sick Leave','','Example')
    rpcsrv.create_expense_account('7350','Vacation - Administrative','','Example')
    rpcsrv.create_expense_account('7351','Vacation Rate Chang - Administrativee','','Example')
    rpcsrv.create_expense_account('7352','Bonuses - Administrative','','Example')
    rpcsrv.create_expense_account('7353','Holidays - Administrative','','Example')
    rpcsrv.create_expense_account('7390','Benefits','','Example')
    rpcsrv.create_expense_account('7481','Equipment Maintenance','','Example')
    rpcsrv.create_expense_account('7482','Facility Maintenance','','Example')
    rpcsrv.create_expense_account('7520','Supplies - Administrative','','Example')
    rpcsrv.create_expense_account('7555','Telephone','','Example')
    rpcsrv.create_expense_account('7570','Outside Services - Administrative','','Example')
    rpcsrv.create_expense_account('7575','Legal & Audit','','Example')
    rpcsrv.create_expense_account('7600','Travel & Entertainment - Administrative','','Example')
    rpcsrv.create_expense_account('7605','Automotive','','Example')
    rpcsrv.create_expense_account('7690','Other Administrative Expense','','Example')
    rpcsrv.create_expense_account('7701','Depreciation','','Example')
    rpcsrv.create_expense_account('7730','Corporate Insurance','','Example')
    rpcsrv.create_expense_account('7740','Real Property Tax','','Example')
    rpcsrv.create_expense_account('7750','Personal Property Tax','','Example')
    rpcsrv.create_expense_account('7752','Sales/Use Tax','','Example')
    rpcsrv.create_expense_account('7755','Other Administrative Tax','','Example')
    rpcsrv.create_expense_account('8100','Loan Interest','','Example')
    rpcsrv.create_expense_account('8900','Other','','Example')
    rpcsrv.create_expense_account('9800','SIT (state income tax)','','Example')
    rpcsrv.create_expense_account('9900','FIT (federal income tax)','','Example')
    rpcsrv.create_liability_account('420','Accounts Payable','','Example')
    rpcsrv.create_liability_account('424','Commissions Payable','','Example')
    rpcsrv.create_liability_account('426','State Sales/Use Tax Payable','','Example')
    rpcsrv.create_liability_account('431','Accrued Wages','','Example')
    rpcsrv.create_liability_account('435','Vacation','','Example')
    rpcsrv.create_liability_account('452','WH-FIT (federal income tax)','','Example')
    rpcsrv.create_liability_account('453','WH-FICA (social security)','','Example')
    rpcsrv.create_liability_account('454','WH-FICM (medicare)','','Example')
    rpcsrv.create_liability_account('455','WH-SIT (state income tax)','','Example')
    rpcsrv.create_liability_account('461','AT-FICA','','Example')
    rpcsrv.create_liability_account('463','AT-FICM','','Example')
    rpcsrv.create_liability_account('465','AT-FUT (federal unemployment tax)','','Example')
    rpcsrv.create_liability_account('467','AT-SUT (state unemployment tax)','','Example')
    rpcsrv.create_liability_account('471','FIT','','Example')
    rpcsrv.create_liability_account('473','SIT','','Example')
    rpcsrv.create_liability_account('475','Property Tax','','Example')
    rpcsrv.create_liability_account('479','Other Accrued Expenses','','Example')
    rpcsrv.create_liability_account('601','Bank Loan','','Example')
    rpcsrv.create_liability_account('901','Common Stock','','Example')
    rpcsrv.create_liability_account('920','Paid-In Capital','','Example')
    rpcsrv.create_liability_account('950','Retained Earnings','','Example')
    rpcsrv.set_parent_account('101','100-129','Example')
    rpcsrv.set_parent_account('110','100-129','Example')
    rpcsrv.set_parent_account('112','100-129','Example')
    rpcsrv.set_parent_account('115','100-129','Example')
    rpcsrv.set_parent_account('117','100-129','Example')
    rpcsrv.set_parent_account('130','130-139','Example')
    rpcsrv.set_parent_account('132','130-139','Example')
    rpcsrv.set_parent_account('139','130-139','Example')
    rpcsrv.set_parent_account('140','140-179','Example')
    rpcsrv.set_parent_account('150','140-179','Example')
    rpcsrv.set_parent_account('170','140-179','Example')
    rpcsrv.set_parent_account('180','180-199','Example')
    rpcsrv.set_parent_account('190','180-199','Example')
    rpcsrv.set_parent_account('210','200-299','Example')
    rpcsrv.set_parent_account('220','200-299','Example')
    rpcsrv.set_parent_account('221','200-299','Example')
    rpcsrv.set_parent_account('229','200-299','Example')
    rpcsrv.set_parent_account('250','200-299','Example')
    rpcsrv.set_parent_account('259','200-299','Example')
    rpcsrv.set_parent_account('270','200-299','Example')
    rpcsrv.set_parent_account('279','200-299','Example')
    rpcsrv.set_parent_account('280','200-299','Example')
    rpcsrv.set_parent_account('289','200-299','Example')
    rpcsrv.set_parent_account('343','300-399','Example')
    rpcsrv.set_parent_account('1100','1000-1999','Example')
    rpcsrv.set_parent_account('1200','1000-1999','Example')
    rpcsrv.set_parent_account('1900','1000-1999','Example')
    rpcsrv.set_parent_account('2100','2000-2999','Example')
    rpcsrv.set_parent_account('2200','2000-2999','Example')
    rpcsrv.set_parent_account('2990','2000-2999','Example')
    rpcsrv.set_parent_account('3210','3000-3999','Example')
    rpcsrv.set_parent_account('3220','3000-3999','Example')
    rpcsrv.set_parent_account('3230','3000-3999','Example')
    rpcsrv.set_parent_account('3295','3000-3999','Example')
    rpcsrv.set_parent_account('3350','3000-3999','Example')
    rpcsrv.set_parent_account('3351','3000-3999','Example')
    rpcsrv.set_parent_account('3352','3000-3999','Example')
    rpcsrv.set_parent_account('3353','3000-3999','Example')
    rpcsrv.set_parent_account('3410','3000-3999','Example')
    rpcsrv.set_parent_account('3420','3000-3999','Example')
    rpcsrv.set_parent_account('3490','3000-3999','Example')
    rpcsrv.set_parent_account('3520','3000-3999','Example')
    rpcsrv.set_parent_account('3550','3000-3999','Example')
    rpcsrv.set_parent_account('3560','3000-3999','Example')
    rpcsrv.set_parent_account('3565','3000-3999','Example')
    rpcsrv.set_parent_account('3570','3000-3999','Example')
    rpcsrv.set_parent_account('5250','5000-5999','Example')
    rpcsrv.set_parent_account('5295','5000-5999','Example')
    rpcsrv.set_parent_account('5350','5000-5999','Example')
    rpcsrv.set_parent_account('5351','5000-5999','Example')
    rpcsrv.set_parent_account('5352','5000-5999','Example')
    rpcsrv.set_parent_account('5353','5000-5999','Example')
    rpcsrv.set_parent_account('5520','5000-5999','Example')
    rpcsrv.set_parent_account('5570','5000-5999','Example')
    rpcsrv.set_parent_account('5580','5000-5999','Example')
    rpcsrv.set_parent_account('5990','5000-5999','Example')
    rpcsrv.set_parent_account('6250','6000-6999','Example')
    rpcsrv.set_parent_account('6251','6000-6999','Example')
    rpcsrv.set_parent_account('6295','6000-6999','Example')
    rpcsrv.set_parent_account('6350','6000-6999','Example')
    rpcsrv.set_parent_account('6351','6000-6999','Example')
    rpcsrv.set_parent_account('6352','6000-6999','Example')
    rpcsrv.set_parent_account('6353','6000-6999','Example')
    rpcsrv.set_parent_account('6502','6000-6999','Example')
    rpcsrv.set_parent_account('6520','6000-6999','Example')
    rpcsrv.set_parent_account('6568','6000-6999','Example')
    rpcsrv.set_parent_account('6570','6000-6999','Example')
    rpcsrv.set_parent_account('6600','6000-6999','Example')
    rpcsrv.set_parent_account('6660','6000-6999','Example')
    rpcsrv.set_parent_account('6661','6000-6999','Example')
    rpcsrv.set_parent_account('7250','7000-7999','Example')
    rpcsrv.set_parent_account('7295','7000-7999','Example')
    rpcsrv.set_parent_account('7301','7000-7999','Example')
    rpcsrv.set_parent_account('7305','7000-7999','Example')
    rpcsrv.set_parent_account('7306','7000-7999','Example')
    rpcsrv.set_parent_account('7340','7000-7999','Example')
    rpcsrv.set_parent_account('7345','7000-7999','Example')
    rpcsrv.set_parent_account('7348','7000-7999','Example')
    rpcsrv.set_parent_account('7350','7000-7999','Example')
    rpcsrv.set_parent_account('7351','7000-7999','Example')
    rpcsrv.set_parent_account('7352','7000-7999','Example')
    rpcsrv.set_parent_account('7353','7000-7999','Example')
    rpcsrv.set_parent_account('7390','7000-7999','Example')
    rpcsrv.set_parent_account('7481','7000-7999','Example')
    rpcsrv.set_parent_account('7482','7000-7999','Example')
    rpcsrv.set_parent_account('7520','7000-7999','Example')
    rpcsrv.set_parent_account('7555','7000-7999','Example')
    rpcsrv.set_parent_account('7570','7000-7999','Example')
    rpcsrv.set_parent_account('7575','7000-7999','Example')
    rpcsrv.set_parent_account('7600','7000-7999','Example')
    rpcsrv.set_parent_account('7605','7000-7999','Example')
    rpcsrv.set_parent_account('7690','7000-7999','Example')
    rpcsrv.set_parent_account('7701','7000-7999','Example')
    rpcsrv.set_parent_account('7730','7000-7999','Example')
    rpcsrv.set_parent_account('7740','7000-7999','Example')
    rpcsrv.set_parent_account('7750','7000-7999','Example')
    rpcsrv.set_parent_account('7752','7000-7999','Example')
    rpcsrv.set_parent_account('7755','7000-7999','Example')
    rpcsrv.set_parent_account('8100','8000-8999','Example')
    rpcsrv.set_parent_account('8900','8000-8999','Example')
    rpcsrv.set_parent_account('9800','9000-9999','Example')
    rpcsrv.set_parent_account('9900','9000-9999','Example')
    rpcsrv.set_parent_account('420','400-429','Example')
    rpcsrv.set_parent_account('424','400-429','Example')
    rpcsrv.set_parent_account('426','400-429','Example')
    rpcsrv.set_parent_account('431','430-459','Example')
    rpcsrv.set_parent_account('435','430-459','Example')
    rpcsrv.set_parent_account('452','430-459','Example')
    rpcsrv.set_parent_account('453','430-459','Example')
    rpcsrv.set_parent_account('454','430-459','Example')
    rpcsrv.set_parent_account('455','430-459','Example')
    rpcsrv.set_parent_account('461','460-479','Example')
    rpcsrv.set_parent_account('463','460-479','Example')
    rpcsrv.set_parent_account('465','460-479','Example')
    rpcsrv.set_parent_account('467','460-479','Example')
    rpcsrv.set_parent_account('471','460-479','Example')
    rpcsrv.set_parent_account('473','460-479','Example')
    rpcsrv.set_parent_account('475','460-479','Example')
    rpcsrv.set_parent_account('479','460-479','Example')
    rpcsrv.set_parent_account('601','600-699','Example')
    rpcsrv.set_parent_account('901','900-999','Example')
    rpcsrv.set_parent_account('920','900-999','Example')
    rpcsrv.set_parent_account('950','900-999','Example')

def init_db_small(rpcsrv):
    master = rpcsrv.create_legal_entity('Master', 'Master Fund','USD')
    feeder_a = rpcsrv.create_legal_entity('FeederA', 'Feeder Fund A','USD')
    feeder_b = rpcsrv.create_legal_entity('FeederB', 'Feeder Fund B','USD')
    
    def create_accounts(company):
        code = company['code']
        rpcsrv.create_asset_account('100', 'Investments','', code)
        rpcsrv.create_asset_account('110', 'Cash Balance','', code)
        rpcsrv.create_liability_account('200', 'Client Shares','', code)

    create_accounts(master)
    create_accounts(feeder_a)
    create_accounts(feeder_b)
    
    rpcsrv.create_accounts_link('FeederA', '100', 'Master', '200')
    rpcsrv.create_accounts_link('FeederB', '100', 'Master', '200')
    
if __name__ =='__main__':

    logging.getLogger().setLevel(logging.DEBUG)
    logging.getLogger('jsonext').setLevel(logging.WARN)
    ch = logging.StreamHandler()
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s', datefmt='%H:%M:%S')
    ch.setFormatter(formatter)
    logging.getLogger().addHandler(ch)
    
    #login = login_sequence('optimacom.sarl', password='*',
    #                       user_input_name='Email', password_input_name='Passwd', 
    #                       auto_register=False, login_path='/', 
    #                       success_url='http://online-acct-sys.appspot.com'
    #                       )
    #rpcsrv = jsonext.ServiceProxy('online-acct-sys.appspot.com', 'jsonrpc', version='2.0')  

    login = login_sequence('test@example.com', user_input_name='email', 
                               password_input_name='password', 
                               auto_register=False, login_path='/',
                               success_url='http://localhost'
                           )
    rpcsrv = jsonext.ServiceProxy('localhost', 'jsonrpc', port=8080, version='2.0')
    
    rpcsrv.set_login_procedure(login)
        
    init_db_small(rpcsrv)
    
    assets, liabilities, earnings, expenses = rpcsrv.get_accounts('Master')
    print '*** assets ***'
    for account in assets:
        print account
        
    print
    print '*** liabilities ***'
    for account in liabilities:
        print account
    
    print 'internal investments'
    print rpcsrv.get_internal_investments('Master')
    print rpcsrv.get_internal_investments('FeederA')
    print rpcsrv.get_internal_investments('FeederB')
    
    print 'internal investors'
    print rpcsrv.get_internal_investors('Master')
    print rpcsrv.get_internal_investors('FeederA')
    print rpcsrv.get_internal_investors('FeederB')
    
