# Generated by Django 2.1.1 on 2018-09-30 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=192, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'oas_account',
            },
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('till_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'oas_accounting_period',
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=192, unique=True)),
            ],
            options={
                'db_table': 'oas_account_type',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=9, unique=True)),
                ('name', models.CharField(max_length=192, unique=True)),
            ],
            options={
                'db_table': 'oas_currency',
            },
        ),
        migrations.CreateModel(
            name='InitialAmount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, default=1.0, max_digits=22)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, default=1.0, max_digits=22)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='oas.Account')),
                ('accounting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initial_amounts', to='oas.AccountingPeriod')),
            ],
            options={
                'db_table': 'oas_initial_amount',
            },
        ),
        migrations.CreateModel(
            name='InternalInvestment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner_account', to='oas.Account', unique=True)),
                ('account_liability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investment_account', to='oas.Account')),
            ],
            options={
                'db_table': 'oas_internal_investment',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('ref_num', models.IntegerField(blank=True, default=False, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, default=1.0, max_digits=22)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, default=1.0, max_digits=22)),
                ('is_debit', models.IntegerField(blank=True, default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='oas.Account')),
            ],
            options={
                'db_table': 'oas_journal_entry',
            },
        ),
        migrations.CreateModel(
            name='JournalEntryGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(null=True)),
                ('accounting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='oas.AccountingPeriod')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='oas.Currency')),
            ],
            options={
                'db_table': 'oas_journal_entry_group',
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=96, unique=True)),
                ('name', models.CharField(max_length=192, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_individual', models.IntegerField(blank=True, default=False)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='oas.Currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_entities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oas_legal_entity',
            },
        ),
        migrations.CreateModel(
            name='TemplateJournalEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, default=1.0, max_digits=22)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, default=1.0, max_digits=22)),
                ('is_debit', models.IntegerField(blank=True, default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_entries', to='oas.Account')),
            ],
            options={
                'db_table': 'oas_template_journal_entry',
            },
        ),
        migrations.CreateModel(
            name='TemplateJournalEntryGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'oas_template_journal_entry_group',
            },
        ),
        migrations.CreateModel(
            name='TemplateSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=192, unique=True)),
                ('description', models.TextField(null=True)),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='oas.LegalEntity')),
                ('template_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='oas.Currency')),
            ],
            options={
                'db_table': 'oas_template_name',
            },
        ),
        migrations.AddField(
            model_name='templatejournalentrygroup',
            name='template_set',
            field=models.ForeignKey(db_column='template_name_id', on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='oas.TemplateSet'),
        ),
        migrations.AddField(
            model_name='templatejournalentry',
            name='template_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='oas.TemplateJournalEntryGroup'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='oas.JournalEntryGroup'),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='oas.LegalEntity'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='oas.AccountType'),
        ),
        migrations.AddField(
            model_name='account',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='oas.LegalEntity'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='oas.Account'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='templateset',
            unique_together={('legal_entity', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='internalinvestment',
            unique_together={('account_asset', 'account_liability')},
        ),
        migrations.AlterUniqueTogether(
            name='initialamount',
            unique_together={('account', 'accounting_period')},
        ),
        migrations.AlterUniqueTogether(
            name='accountingperiod',
            unique_together={('legal_entity', 'name'), ('legal_entity', 'till_date')},
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('legal_entity', 'name'), ('legal_entity', 'code')},
        ),
    ]
